receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlp/elastic:
    endpoint: "http://apm-server:8200"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/elastic ]