version: "3.7"
services:

  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Password123
      - TZ=America/Sao_Paulo

volumes:
  sqlserverdata: