version: "3.7"
services:
  rabbitmq:
    image: rabbitmq:3.7-management
    deploy:
      placement:
        constraints: 
          - node.labels.OS == linux
          - node.ip == 140.0.6.205
      labels:
        - traefik.port=15672
        - traefik.enable=true
        - traefik.frontend.rule=Host:rabbit.de.autbank.net
    hostname: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - web

volumes:
  rabbitmqdata:

networks:
  web: 
    external: true