version: "3.7"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    deploy:
      placement:
        constraints: 
          - node.labels.OS == linux
          - node.ip == 140.0.6.205
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - "1450:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=@Password123
      - TZ=America/Sao_Paulo
    networks:
      - web

volumes:
  sqlserverdata:

networks:
  web: 
    external: true