version: '3.7'

services:
  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888


  kafka1:
    image: bitnami/kafka:2.4.0
    ports:
      - "30520:30520"
      - "2564:2564"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:30520"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://140.6.254.242:30520"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_BROKER_ID: "1"
      KAFKA_CFG_NUM_PARTITIONS: "15"
      KAFKA_CFG_PORT: "30520"
      JMX_PORT: 2564
    depends_on:
      - zoo1