groups:
- name: pixAlerts
  rules:
  - alert: 50PercentOver6Secounds
    expr: (sum(increase(http_server_requests_seconds_count{application="JDHCX",status=~"2..",uri="/user"}[30m])+1) - sum(increase(http_server_requests_seconds_bucket { uri="/user",application="JDHCX", status=~"2..", le="6.0"}[30m]))) / sum(increase(http_server_requests_seconds_count { uri="/user",application="JDHCX", status=~"2.."}[30m])+1) * 100 > 50
    for: 15s
    labels:
      severity: critical
    annotations:
      summary: Host {{ $labels.instance }} of {{ $labels.job }}
  - alert: 1PercentOver10Secounds
    expr: (sum(increase(http_server_requests_seconds_count{application="JDHCX",status=~"2..",uri="/user"}[30m])+1) - sum(increase(http_server_requests_seconds_bucket { uri="/user",application="JDHCX", status=~"2..", le="10.0"}[30m]))) / sum(increase(http_server_requests_seconds_count { uri="/user",application="JDHCX", status=~"2.."}[30m])+1) * 100 > 1
    for: 15s
    labels:
      severity: critical
    annotations:
      summary: Host {{ $labels.instance }} of {{ $labels.job }}