global:
  scrape_interval:     15s
  evaluation_interval: 5s

  external_labels:
      monitor: 'prometheus-stack-monitor'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#  - "/etc/prometheus/rules/alerts/gi-alert-rules-dict.yaml"
#  - "/etc/prometheus/rules/alerts/gi-alert-rules-icom.yaml"
#  - "/etc/prometheus/rules/records/gi-record-rules-dict.yaml"
#  - "/etc/prometheus/rules/records/gi-record-rules-icom.yaml"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 15s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: 'app-local'
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
    - targets: ['172.21.128.1:9090']

  - job_name: 'app-docker'
    metrics_path: '/metrics'
    scrape_interval: 1s
    static_configs:
    - targets: ['app:9090']