global:
  scrape_interval:     5s
  evaluation_interval: 5s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus-stack-monitor'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - 'alertmanager:9093'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "/etc/prometheus/alert.rules"
  # - "first.rules"
  # - "second.rules"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 10s
    scrape_timeout: 5s

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-test'
    metrics_path: '/prometheus'
    scrape_interval: 1s
    static_configs:
    - targets: ['140.6.254.102:19090']