version: '3'

services:

  elastic_opendistro:
    image: amazon/opendistro-for-elasticsearch:1.3.0
    environment:
      - discovery.type=single-node
      - http.host=0.0.0.0
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
      - opendistro_security.ssl.http.enabled=false
    volumes:
      - elastic_opendistro:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
      - 9700:9600 # required for Performance Analyzer

  kibana_opendistro:
    image: amazon/opendistro-for-elasticsearch-kibana:1.3.0
    ports:
      - 5701:5601
    environment:
      ELASTICSEARCH_URL: http://elastic_opendistro:9200
      ELASTICSEARCH_HOSTS: http://elastic_opendistro:9200

volumes:
  elastic_opendistro:
  kibana_opendistro: