version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      discovery.type: single-node
      http.host: 0.0.0.0
    volumes:
      - elastichData:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    deploy:
    depends_on:
        - elasticsearch
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_URL: http://elasticsearch:9200
      XPACK_SECURITY_ENABLED: "true"
      XPACK_GRAPH_ENABLED: "true"
      XPACK_WATCHER_ENABLED: "true"
      XPACK_ML_ENABLED: "true"
      XPACK_MONITORING_ENABLED: "true"
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ports:
      - 5601:5601

volumes:
  elastichData: