version: '3.7'
services:
  redis:
    image: redis:6.0.6
    command: ["redis-server", "--appendonly", "yes","--requirepass","Redis2019!"]
    ports:
    - "6379:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=redis:6379
      - REDIS_PASSWORD=Redis2019!
    ports:
      - 8081:8081
    depends_on:
      - redis